name = "Alexandria"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://awsusergroup.org/"
tags = []
features = []
min_version = "0.20"

[author]
  name = "Donnie Prakoso"
  homepage = "https://donnie.id"

